### ISSUE TITLE
recv() doesn't guarantee receiving the full message

### ISSUE THREAD

**Issue by spicy-sauce** [guyskk/pybeautifier#6]
See this:
https://stackoverflow.com/questions/47758023/python3-socket-random-partial-result-on-socket-receive

Method recv() does not guarantee receiving the full message in the first call so you have to try getting the full message by calling recv() multiple times.

**Comment by guyskk** [comment]
Uploaded to PYPI: https://pypi.org/project/pybeautifier/0.1.3/
